# Generated by Django 4.0.3 on 2022-07-22 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorie', '0001_initial'),
        ('sous_categorie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sous_categorie',
            name='categorie',
        ),
        migrations.AddField(
            model_name='sous_categorie',
            name='Categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categorie.categorie'),
        ),
    ]
