# Generated by Django 4.0.3 on 2022-08-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='Categorie',
            field=models.TextField(max_length=30, null=True),
        ),
    ]
