# Generated by Django 4.0.3 on 2022-07-22 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sous_categorie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero_inventaire', models.TextField(max_length=200, null=True)),
                ('Numero_serie', models.TextField(max_length=200, null=True)),
                ('Marque', models.TextField(max_length=200, null=True)),
                ('Etat', models.IntegerField(choices=[(1, 'Très bon'), (2, 'Bon'), (3, 'Moyen'), (4, 'Mauvais'), (5, 'En panne')], unique=True)),
                ('Date_acquisition', models.DateTimeField(null=True)),
                ('Type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sous_categorie.sous_categorie')),
            ],
        ),
    ]
