# Generated by Django 4.0.3 on 2022-07-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiel', '0006_alter_materiel_etat'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiel',
            name='Modele',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
