# Generated by Django 4.0.3 on 2022-07-28 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiel', '0007_materiel_modele'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiel',
            name='Modele',
        ),
    ]
