# Generated by Django 4.0.3 on 2022-08-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiel', '0008_remove_materiel_modele'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiel',
            name='Model',
            field=models.TextField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='Etat',
            field=models.TextField(choices=[('Aucun', 'Aucun'), ('Très bon', 'Très bon'), ('bon', 'Bon'), ('Moyen', 'Moyen'), ('Mauvais', 'Mauvais'), ('En panne', 'En panne')], max_length=30),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='Marque',
            field=models.TextField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='Numero_inventaire',
            field=models.TextField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='Numero_serie',
            field=models.TextField(max_length=30, null=True),
        ),
    ]
