# Generated by Django 4.0.3 on 2022-08-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiel', '0009_materiel_model_alter_materiel_etat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiel',
            name='Etat',
            field=models.TextField(choices=[('Aucun', 'Aucun'), ('Très bon', 'Très bon'), ('Bon', 'Bon'), ('Moyen', 'Moyen'), ('Mauvais', 'Mauvais'), ('En panne', 'En panne')], max_length=30),
        ),
    ]
